{
 "title": "Model observability dashboard",
 "time": { "from": "2024-08-07T16:18:15.261Z", "to": "2024-08-07T16:18:18.239Z" },
 "panels": [
  {
   "title": "Distribution of classes",
   "type": "timeseries",
   "description": "Shows what fraction of all the predictions each class makes up.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select timestamp,class_0_frac,class_1_frac,class_2_frac,class_3_frac from metrics;"
    }
   ]
  },
  {
   "title": "Prediction drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select timestamp,prediction_drift from metrics;"
    }
   ]
  },
  {
   "title": "Processed cases",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "rawSql": "select * from ledger" }
   ]
  }
 ]
}